
INSERT INTO `roles` (`name`, `title`)
VALUES
	('superadmin', 'Superadmin'),
    ('admin', 'Admin'),
    ('gs', 'Geschäftsstelle'),
    ('mg', 'Mitglied'),
    ('zuechter', 'Züchter'),
    ('schatzmeister', 'Schatzmeister'),
    ('kassenwart', 'Kassenwart'),
    ('pressewart', 'Pressewart'),
    ('schriftfuehrer', 'Schriftführer'),
    ('vorstand', 'Vorstand'),
    ('vorstand-erweitert', 'Vorstand Erweitert'),
    ('zw', 'Zuchtwart'),
    ('zw-anwaerter', 'Zuchtwartanwärter'),
    ('rzw', 'Rassezuchtwart'),
    ('rzw-sv', 'Rassezuchtwart Stellvertreter'),
    ('rzw-chessy', 'Rassezuchtwart Chessy'),
    ('rzw-curly', 'Rassezuchtwart Curly'),
    ('rzw-flat', 'Rassezuchtwart Flat'),
    ('rzw-golden', 'Rassezuchtwart Golden'),
    ('rzw-labrador', 'Rassezuchtwart Labrador'),
    ('rzw-nsdt', 'Rassezuchtwart NSDT'),
    ('rzw-chessy-sv', 'Rassezuchtwart Chessy Stellvertreter'),
    ('rzw-curly-sv', 'Rassezuchtwart Curly Stellvertreter'),
    ('rzw-flat-sv', 'Rassezuchtwart Flat Stellvertreter'),
    ('rzw-golden-sv', 'Rassezuchtwart Golden Stellvertreter'),
    ('rzw-labrador-sv', 'Rassezuchtwart Labrador Stellvertreter'),
    ('rzw-nsdt-sv', 'Rassezuchtwart NSDT Stellvertreter'),
    ('sonderleiter', 'Sonderleiter'),
    ('richter', 'Richter'),
    ('richteranwaerter', 'Richteranwärter'),
    ('verbandsrichter', 'Verbandsrichter'),
    ('wesensrichter', 'Wesensrichter'),
    ('fw-richter', 'Formwertrichter'),
    ('dummyrichter', 'Dummyrichter'),
    ('bgh-richter', 'Begleithunderichter'),
    ('ft-richter', 'Field-Trial-Richter'),
    ('jagdrichter', 'Jagdrichter'),
    ('jagdrichter-ft', 'Jagdrichter/FT'),
    ('vereins-schweiss-richter', 'Vereins-Schweiß-Richter'),
    ('anwaerter-verbandsrichter', 'Anwärter-Verbandsrichter'),
    ('anwaerter-fw-richter', 'Anwärter-Formwertrichter'),
    ('anwaerter-wesensrichter', 'Anwärter-Wesensrichter'),
    ('anwaerter-bgh-richter', 'Anwärter-Begleithunderichter'),
    ('anwaerter-dummyrichter', 'Anwärter-Dummyrichter'),
    ('anwaerter-vereins-schweiss-richter', 'Anwärter-Vereins-Schweiß-Richter'),
    ('ausbilder', 'Ausbilder'),
    ('ausbilder-anwaerter', 'Ausbilder-Anwärter'),
    ('obmann-verbandsrichter', 'Obmann der Verbandsrichter'),
    ('obmann-leistungsrichter', 'Obmann der Leistungsrichter'),
    ('obmann-zuchtwarte', 'Obmann für Zuchtwarte'),
    ('obmann-ausstellungswesen', 'Obmann für Ausstellungswesen'),
    ('koordination-ansprechpartner-wesenstests', 'Koordination&Ansprechpartner Wesenstests'),
    ('ehrenrat', 'Ehrenrat'),
    ('satzungskommission', 'Satzungskommission'),
    ('trial-ausschuss', 'Trial Ausschuss'),
    ('fci-delegierter', 'FCI Delegierter'),
    ('gutachter', 'Gutachter'),
    ('obergutachter', 'Obergutachter');
